header_title: Iqlusion Liquid Staking Working Group
plugins:
  - jekyll-paginate
  - jekyll-contentblocks
svg:
  optimize: true

paginate: 5
paginate_path: "/blog/page-:num/"
collections:
  meeting_notes:
    output: true
    permalink: /meeting-notes/:title

defaults:
  - scope:
      path: ""
      type: "meeting_notes"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "posts"
    values:
      with_other_posts: true
      layout: "post"
