header_title: Iqlusion Liquid Staking Working Group
plugins:
  - jekyll-inline-svg
  - jekyll-paginate
  - jekyll-contentblocks
svg:
  optimize: true

paginate: 5
paginate_path: "/blog/page-:num/"
collections:
  - meeting_notes
